pipeline:
  publish:
    image: plugins/docker
    privileged: true
    repo: pingu/deptifree
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: [ master ]
  deploy:
    image: pingu/drone-plugin-kontena:latest
    secrets: [ kontena_token, kontena_url, kontena_grid ]
    kontena_stack: deptifree
    when:
      status: [ success ]
      branch: [ master ]
