# Generated by Django 2.1.5 on 2019-02-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('purpose', models.TextField(blank=True, default='', max_length=100)),
                ('value', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexDept',
            fields=[
                ('dept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dept.Dept')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexdept_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
            bases=('dept.dept',),
        ),
        migrations.CreateModel(
            name='SimpleDept',
            fields=[
                ('dept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dept.Dept')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simpledept_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
            bases=('dept.dept',),
        ),
        migrations.AddField(
            model_name='dept',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to=settings.AUTH_USER_MODEL),
        ),
    ]
