# Generated by Django 2.1.5 on 2019-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_auto_20190201_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
