# Generated by Django 2.1.5 on 2019-02-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_auto_20190202_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='creator',
        ),
    ]
