# Generated by Django 2.1.5 on 2019-02-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dept', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='depts', to=settings.AUTH_USER_MODEL),
        ),
    ]
