# Generated by Django 2.1.5 on 2019-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
